-- MySQL Script generated by MySQL Workbench
-- Tue Sep 26 19:56:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Disciplinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Disciplinas` (
  `idDisciplinas` INT NOT NULL,
  `NameDisciplinas` VARCHAR(45) NULL,
  `PreRequisitosDisciplinas` VARCHAR(45) NULL,
  `CreditosDisciplina` VARCHAR(45) NULL,
  `DuracaoTotalDisciplina` INT NULL,
  `CapacidadeTotalDisciplina` INT NULL,
  PRIMARY KEY (`idDisciplinas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamentos` (
  `idDepartamentos` INT NOT NULL,
  `NameDepartamentos` VARCHAR(45) NULL,
  `CursosVinculados` VARCHAR(45) NULL,
  PRIMARY KEY (`idDepartamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DataPeriodoLetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DataPeriodoLetivo` (
  `idDataPeriodoLetivo` INT NOT NULL,
  `InicioPeriodoLetivo` DATE NULL,
  `FinalPeriodoLetivo` DATE NULL,
  PRIMARY KEY (`idDataPeriodoLetivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Campus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Campus` (
  `idCampus` INT NOT NULL,
  `NameCampus` VARCHAR(45) NULL,
  `EnderecoCampus` VARCHAR(45) NULL,
  `BairroCampus` VARCHAR(45) NULL,
  `CidadeCampus` VARCHAR(45) NULL,
  `EstadoCampus` VARCHAR(45) NULL,
  `PaísCampus` VARCHAR(45) NULL,
  `CapacidadeTotalCampus` INT NULL,
  PRIMARY KEY (`idCampus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `idProfessor` INT NOT NULL,
  `FNameProfessor` VARCHAR(20) NULL,
  `LNameProfessor` VARCHAR(45) NULL,
  `BirthDate` DATE NULL,
  `idDisciplinas` INT NOT NULL,
  `idDepartamentos` INT NOT NULL,
  `idDataPeriodoLetivo` INT NOT NULL,
  `Campus_idCampus` INT NOT NULL,
  PRIMARY KEY (`idProfessor`, `idDisciplinas`, `idDepartamentos`, `idDataPeriodoLetivo`, `Campus_idCampus`),
  INDEX `fk_Professor_Disciplinas_idx` (`idDisciplinas` ASC) VISIBLE,
  INDEX `fk_Professor_Departamentos1_idx` (`idDepartamentos` ASC) VISIBLE,
  INDEX `fk_Professor_DataPeriodoLetivo1_idx` (`idDataPeriodoLetivo` ASC) VISIBLE,
  INDEX `fk_Professor_Campus1_idx` (`Campus_idCampus` ASC) VISIBLE,
  CONSTRAINT `fk_Professor_Disciplinas`
    FOREIGN KEY (`idDisciplinas`)
    REFERENCES `mydb`.`Disciplinas` (`idDisciplinas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Departamentos1`
    FOREIGN KEY (`idDepartamentos`)
    REFERENCES `mydb`.`Departamentos` (`idDepartamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_DataPeriodoLetivo1`
    FOREIGN KEY (`idDataPeriodoLetivo`)
    REFERENCES `mydb`.`DataPeriodoLetivo` (`idDataPeriodoLetivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_Campus1`
    FOREIGN KEY (`Campus_idCampus`)
    REFERENCES `mydb`.`Campus` (`idCampus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
